# Generated by Django 4.1.5 on 2023-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thinkingFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('function', models.CharField(choices=[('Perceive', 'Perceive'), ('Judgment', 'Judgment')], max_length=20)),
                ('fType', models.CharField(choices=[('Sight', 'Sight'), ('Sound', 'Sound'), ('Touch', 'Touch'), ('Smell', 'Smell'), ('Taste', 'Taste'), ('Feeling', 'Feeling'), ('Thinking', 'Thinking')], max_length=20)),
                ('time', models.CharField(choices=[('Past', 'Past'), ('Now', 'Now'), ('Feature', 'Feature'), ('Possibility', 'possibility')], max_length=20)),
                ('decideTo', models.CharField(max_length=50)),
            ],
        ),
    ]
