# Generated by Django 4.1.5 on 2023-03-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkingAnalyzer', '0002_thinkingfunction_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thinkingfunction',
            old_name='Detail',
            new_name='detail',
        ),
    ]
