# Generated by Django 4.1.5 on 2023-03-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thinkingAnalyzer', '0003_rename_detail_thinkingfunction_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinkingfunction',
            name='decideTo',
        ),
        migrations.RemoveField(
            model_name='thinkingfunction',
            name='fType',
        ),
        migrations.RemoveField(
            model_name='thinkingfunction',
            name='function',
        ),
        migrations.RemoveField(
            model_name='thinkingfunction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='thinkingfunction',
            name='target',
        ),
        migrations.RemoveField(
            model_name='thinkingfunction',
            name='time',
        ),
        migrations.AlterField(
            model_name='thinkingfunction',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='thinkingFunctionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=50)),
                ('function', models.CharField(choices=[('Perceive', 'Perceive'), ('Judgment', 'Judgment')], max_length=20)),
                ('fType', models.CharField(choices=[('Sight', 'Sight'), ('Sound', 'Sound'), ('Touch', 'Touch'), ('Smell', 'Smell'), ('Taste', 'Taste'), ('Feeling', 'Feeling'), ('Thinking', 'Thinking')], max_length=20)),
                ('time', models.CharField(choices=[('Past', 'Past'), ('Now', 'Now'), ('Feature', 'Feature'), ('Possibility', 'possibility')], max_length=20)),
                ('decideTo', models.CharField(max_length=50)),
                ('thinkingFunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thinkingAnalyzer.thinkingfunction')),
            ],
        ),
    ]
